-- Supprimer la table Adherent si elle existe déjà
DROP TABLE Adherent IF EXISTS;
DROP TABLE Recette IF EXISTS;
DROP TABLE Event IF EXISTS;

-- Créer la table Adherent
CREATE TABLE Adherent (
    idAdh INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL,
    PRIMARY KEY (idAdh)
);

-- Créer la table Recette
CREATE TABLE Recette (
    idRec INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    ingredients VARCHAR(500), -- Stocker les ingrédients sous forme de chaîne
    etapes VARCHAR(1000), -- Stocker les étapes sous forme de chaîne
    photo VARCHAR(255),
    auteur VARCHAR(100),
    PRIMARY KEY (idRec)
);

-- Créer la table Event
CREATE TABLE Event (
    idEvent INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    titre VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    lieu VARCHAR(100),
    description VARCHAR(500),
    auteur VARCHAR(100),
    PRIMARY KEY (idEvent)
);



commit;

